### ISSUE TITLE
Android SDK > 32 Support

### ISSUE THREAD

**Issue by Galileon-venta** [Cap-go/capacitor-flash#26]
Hello, I've tried to add a flashlight to my project that also uses @capgo/barcode-scanner... it works fine on ios but it seems that android support is lacking. CapacitorFlash.isAvailable returns true but neither toggle nor setActive are working (returning false) without any indication why. It seems that this might be the same Problem @macordalfy mentioned in #2 and #4.

**Comment by riderx** [comment]
Hello can you provide a reproduction repo ? as you can see i cannot reproduce on my side

**Comment by Galileon-venta** [comment]
Hi, i've granted you access to my minimal reproduce based on a fresh ionic install i moved over the scanner page module entirely and slimmed out translation etc. https://github.com/Galileon-venta/min_rep_flash

I tested with an iPhone 6S running latest iOS 15 working fine
A Samsung Galaxy S22 running latest Android 13 OneUI 5.1 not working
A Samsung Galaxy A5 running Android 11 LineageOS 18.1 not working

**Comment by Galileon-venta** [comment]
Ok, the problem is that the barcode scanner creates a session with the camera and this plugin is not able to open another session in parallel; @macordalfy just use the torch related api within the barcode plugin. 

Ill close this issue since it is misleading the only issues that @riderx could change is the documentation (the max sdk version parameter is not required for me) and the  native error handling within the api for better debug purposes.
